### ISSUE TITLE
Class cast exception in Files[IO].writeAll

### ISSUE THREAD

**Issue by rehanone** [typelevel/fs2#2380]
I am trying to migrate [fs2-ftp](https://github.com/regis-leray/fs2-ftp) to version 3 and we are seeing a very strange issue with Files[IO].writeAll function as seen in this [PR#132](https://github.com/regis-leray/fs2-ftp/pull/132).

The error is:

```
[info]   java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [B ([Ljava.lang.Object; and [B are in module java.base of loader 'bootstrap')
[info]   at fs2.Chunk.toByteBuffer(Chunk.scala:327)
[info]   at fs2.io.file.FileHandle$$anon$1.$anonfun$write$1(FileHandle.scala:151)
[info]   at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
[info]   at cats.effect.IOFiber.blockingR(IOFiber.scala:1136)
[info]   at cats.effect.IOFiber.run(IOFiber.scala:128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
```

Unfortunately my understanding of v3 is still limited at best hwoever, @regis-leray suggested that this issue might have been a bug in fs2 in the past as mentioned here: https://github.com/typelevel/fs2/pull/1161#discussion_r195890105

Would really appreciate if this issue can either be resolved in fs2 or perhaps point a different approach to avoid it in fs2-ftp.

**Comment by ScalaWilliam** [comment]
Can you check which JDK version you are using?

**Comment by mpilquist** [comment]
Reproduction:

```scala
scala> Chunk(1.toByte, 2.toByte).map(identity).toByteBuffer
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [B ([Ljava.lang.Object; and [B are in module java.base of loader 'bootstrap')
  at fs2.Chunk.toByteBuffer(Chunk.scala:327)
  ... 38 elided
```

**Comment by mpilquist** [comment]
Fix:
```scala
diff --git a/core/shared/src/main/scala/fs2/Chunk.scala b/core/shared/src/main/scala/fs2/Chunk.scala
index 14040f76d..6a5d59a60 100644
--- a/core/shared/src/main/scala/fs2/Chunk.scala
+++ b/core/shared/src/main/scala/fs2/Chunk.scala
@@ -323,7 +323,7 @@ abstract class Chunk[+O] extends Serializable with ChunkPlatform[O] { self =>
   def toByteBuffer[B >: O](implicit ev: B =:= Byte): JByteBuffer = {
     val _ = ev // Convince scalac that ev is used
     this match {
-      case c: Chunk.ArraySlice[_] =>
+      case c: Chunk.ArraySlice[_] if c.values.isInstanceOf[Array[Byte]] =>
         JByteBuffer.wrap(c.values.asInstanceOf[Array[Byte]], c.offset, c.length)
       case c: Chunk.ByteBuffer =>
         val b = c.buf.asReadOnlyBuffer
```

**Comment by mpilquist** [comment]
No problem -- I'll try to get a PR together today and then we can do a patch release. If someone beats me to the PR, that would be great. I'd have opened it already but my workspace has a partial fix for another issue and haven't had time to properly stash/etc. :)

**Comment by rehanone** [comment]
@mpilquist , Thanks! I will try to give it a go and submit a PR for this.
