### ISSUE TITLE
fs2.io.readOutputStream hangs when triggering effect error using cats.data.EitherT

### ISSUE THREAD

**Issue by mrdziuban** [typelevel/fs2#2647]
When using `fs2.io.readOutputStream` in combination with an effect type that uses `cats.data.EitherT`, a failure in the effect (i.e. a `Left` within the `EitherT`) does not terminate the `Stream`, causing the code to hang indefinitely.

I can reproduce this on both v2.5.9 and v3.1.3 using the code in this repository: https://github.com/mrdziuban/fs2-readOutputStream-EitherT. The code in each `Test.scala` times out the `IO` after 5 seconds to demonstrate the problem, without the timeout it will run forever.

I ran a thread dump with `jstack` hoping to find something that was blocking execution but didn't see anything that stood out. The full output is below in case it's helpful.

<details><summary>expand thread dump</summary>

```
2021-09-28 09:49:46
Full thread dump OpenJDK 64-Bit Server VM (25.302-b00 mixed mode):

"Attach Listener" #19 daemon prio=9 os_prio=31 tid=0x00007fec80810800 nid=0x1107 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"io-blocking-0" #18 daemon prio=5 os_prio=31 tid=0x00007fec7e1fa800 nid=0xa103 waiting on condition [0x000070000ed30000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c002daf8> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"io-compute-7" #17 daemon prio=5 os_prio=31 tid=0x00007fec80807000 nid=0x5f03 waiting on condition [0x000070000ec2d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-6" #16 daemon prio=5 os_prio=31 tid=0x00007fec807da000 nid=0x5d03 waiting on condition [0x000070000eb2a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-5" #15 daemon prio=5 os_prio=31 tid=0x00007fec7e1e7800 nid=0xa303 waiting on condition [0x000070000ea27000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-4" #14 daemon prio=5 os_prio=31 tid=0x00007fec7e1e6800 nid=0xa503 waiting on condition [0x000070000e924000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-3" #13 daemon prio=5 os_prio=31 tid=0x00007fec7e1e5800 nid=0xa603 waiting on condition [0x000070000e821000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-2" #12 daemon prio=5 os_prio=31 tid=0x00007fec7e1e5000 nid=0x5903 waiting on condition [0x000070000e71e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-1" #11 daemon prio=5 os_prio=31 tid=0x00007fec807d9000 nid=0x5803 waiting on condition [0x000070000e61b000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"io-compute-0" #10 daemon prio=5 os_prio=31 tid=0x00007fec807f1800 nid=0x5703 waiting on condition [0x000070000e518000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0029598> (a cats.effect.unsafe.WorkStealingThreadPool)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at cats.effect.unsafe.WorkerThread.parkLoop$1(WorkerThread.scala:244)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:375)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007fec7f84f800 nid=0x4003 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007fec7f824000 nid=0x4203 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007fec8003a000 nid=0x3f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007fec80039000 nid=0x4403 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007fec7e043000 nid=0x4503 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007fec7e03e800 nid=0x3c03 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007fec7f805800 nid=0x4b03 in Object.wait() [0x000070000dd00000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0003a78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000006c0003a78> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007fec7f802800 nid=0x3403 in Object.wait() [0x000070000dbfd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0019bc0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c0019bc0> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007fec7e802000 nid=0x1903 waiting on condition [0x000070000d1df000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c002a408> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at cats.effect.IOPlatform.$anonfun$unsafeRunTimed$2(IOPlatform.scala:86)
	at cats.effect.IOPlatform$$Lambda$61/2129221032.apply$mcZ$sp(Unknown Source)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.scala:17)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.package$.blocking(package.scala:124)
	at cats.effect.IOPlatform.unsafeRunTimed(IOPlatform.scala:86)
	at cats.effect.IOPlatform.unsafeRunSync(IOPlatform.scala:46)
	at example.Test$.main(Test.scala:14)
	at example.Test.main(Test.scala)

"VM Thread" os_prio=31 tid=0x00007fec8000c800 nid=0x4c03 runnable

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007fec7e80e000 nid=0x2b07 runnable

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007fec7e016000 nid=0x2c03 runnable

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007fec7e016800 nid=0x5203 runnable

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007fec7e017800 nid=0x2e03 runnable

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007fec80000000 nid=0x5103 runnable

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007fec7e018000 nid=0x4f03 runnable

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007fec7e019000 nid=0x4e03 runnable

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007fec7e019800 nid=0x3103 runnable

"VM Periodic Task Thread" os_prio=31 tid=0x00007fec7f858800 nid=0xa903 waiting on condition

JNI global references: 850
```

</details>

**Comment by vasilmkd** [comment]
I haven't done a serious analysis, but this may point to a bigger issue with the `concurrently` operator and how it behaves with short-circuiting transformers.

**Comment by mpilquist** [comment]
No shortage of issues with `EitherT` in the past: https://github.com/typelevel/fs2/search?q=eithert&type=issues
