### ISSUE TITLE
java.net.ConnectException: Operation timed out java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)

### ISSUE THREAD

**Issue by dfurmans** [typelevel/fs2#3436]
App stack 
--------------
lazy val http4sVersion = "0.23.18"
lazy val catsEffectVersion = "3.4.5"
lazy val catsCoreVersion = "2.9.0"
lazy val fs2Version = "3.5.0"
lazy val doobieVersion = "1.0.0-RC1"
lazy val circeVersion = "0.15.0-M1"

on Kubernetes looks like service can not be run.

`at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:256)
at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:202)
at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
at async_ @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$7(SocketGroupPlatform.scala:60)
at blocking @ fs2.io.net.tls.TLSContextCompanionPlatform$BuilderCompanionPlatform$AsyncBuilder.system(TLSContextPlatform.scala:268)
at map @ com.comcast.ip4s.SocketAddressCompanionPlatform$ResolveOps.resolve(SocketAddressPlatform.scala:39)
at flatMap @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.connect$1(SocketGroupPlatform.scala:59)
at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.$anonfun$client$4(SocketGroupPlatform.scala:56)
at onError$extension @ org.typelevel.keypool.KeyPool$Builder.keepRunning$1(KeyPool.scala:370)
at delay @ fs2.io.net.SocketGroupCompanionPlatform$AsyncSocketGroup.setup$1(SocketGroupPlatform.scala:53)

**Comment by mpilquist** [comment]
That stack trace indicates your app can't reach the destination host. That's very likely to be due to some environmental issues like firewalls, proxy settings, networking configuration, etc.

**Comment by dfurmans** [comment]
Thanks @mpilquist 
The think is that our CI is deploying an app into CaaS env, and the app is up-and-running - we can see it from the logs. 
However the kubernetes readiness URI can not be reached. the stack is exactly from that point.

**Comment by dfurmans** [comment]
our issue has been related with Kubernetes to use an external URL for configuration API, and that provokes, that the application went outside the cluster to rejoin it afterwards - and here were a point of failure.
Closing it.
